'use client';

import { useEffect, useMemo, useState } from 'react';
import { BarChart3, Clock3, ImagePlus, LayoutGrid, Menu, Minus, Plus, Receipt, Settings2, ShoppingBag, Trash2, X } from 'lucide-react';
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import MenuManager from '@/components/menu-manager';
import type { Product, Sale } from '@/lib/types';
import { supabase } from '@/lib/supabase';
import { BUSINESS_DAY_RESET_HOUR, businessDayBounds, businessDayKey, formatBusinessDay, isInBusinessDay } from '@/lib/business-day';

type Tab = 'counter' | 'history' | 'analytics' | 'menu';
type Mode = 'daily' | 'monthly' | 'custom' | 'yearly';
const money = (n:number)=>`₹${n.toLocaleString('en-IN',{maximumFractionDigits:0})}`;
const empty: Product[]=[];
const keyMonth=(k:string)=>k.slice(0,7), keyYear=(k:string)=>k.slice(0,4);
function range(mode:Mode,d:string,m:string,y:string,cs:string,ce:string){
 if(mode==='daily')return businessDayBounds(d); if(mode==='monthly'){const [yy,mm]=m.split('-').map(Number);return{start:businessDayBounds(`${yy}-${String(mm).padStart(2,'0')}-01`).start,end:businessDayBounds(`${yy}-${String(mm+1).padStart(2,'0')}-01`).start}} if(mode==='yearly')return{start:businessDayBounds(`${y}-01-01`).start,end:businessDayBounds(`${Number(y)+1}-01-01`).start}; const a=cs||d,b=ce||a,s=a<=b?a:b,e=a<=b?b:a;return{start:businessDayBounds(s).start,end:businessDayBounds(e).end};
}

export default function PosApp(){
 const today=businessDayKey(); const [tab,setTab]=useState<Tab>('counter'); const [products,setProducts]=useState<Product[]>(empty); const [sales,setSales]=useState<Sale[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [customOpen,setCustomOpen]=useState(false); const [customPrice,setCustomPrice]=useState(''); const [historyDate,setHistoryDate]=useState(today); const [mode,setMode]=useState<Mode>('daily'); const [daily,setDaily]=useState(today); const [month,setMonth]=useState(keyMonth(today)); const [year,setYear]=useState(keyYear(today)); const [cs,setCs]=useState(today); const [ce,setCe]=useState(today); const [editing,setEditing]=useState<Product|null>(null);
 const load=async()=>{if(!supabase){setError('Connect Supabase in Vercel environment variables.');setLoading(false);return} setLoading(true);const [p,s]=await Promise.all([supabase.from('products').select('*').order('name'),supabase.from('sales').select('*').order('timestamp',{ascending:false})]);if(p.error||s.error)setError(p.error?.message||s.error?.message||'Could not load store data.');else{setProducts((p.data||[]).map(x=>({...x,daily_count:0})));setSales((s.data||[]) as Sale[])}setLoading(false)};
 useEffect(()=>{load()},[]);
 const todaySales=useMemo(()=>sales.filter(s=>isInBusinessDay(s.timestamp,today)),[sales,today]); const total=useMemo(()=>todaySales.reduce((a,s)=>a+s.price_charged,0),[todaySales]); const counts=useMemo(()=>Object.fromEntries(products.map(p=>[p.id,todaySales.filter(s=>s.product_id===p.id).length])),[products,todaySales]); const hist=sales.filter(s=>isInBusinessDay(s.timestamp,historyDate)).sort((a,b)=>b.timestamp.localeCompare(a.timestamp)); const r=range(mode,daily,month,year,cs,ce); const asales=sales.filter(s=>{const t=Date.parse(s.timestamp);return t>=r.start.getTime()&&t<r.end.getTime()}); const revenue=asales.reduce((a,s)=>a+s.price_charged,0),profit=asales.reduce((a,s)=>a+s.profit_recorded,0);
 const add=async(p:Product)=>{if(!supabase)return;const row={product_id:p.id,product_name:p.name,price_charged:p.price,profit_recorded:p.profit_margin};const {data,error:e}=await supabase.from('sales').insert(row).select().single();if(e)setError(e.message);else if(data)setSales(s=>[data as Sale,...s])};
 const remove=async(p:Product)=>{if(!supabase)return;const b=businessDayBounds(today);const {data,error:e}=await supabase.rpc('delete_latest_sale',{p_product_id:p.id,p_business_day_start:b.start.toISOString(),p_business_day_end:b.end.toISOString()});if(e)setError(e.message);else if(data)setSales(s=>s.filter(x=>x.id!==data))};
 const custom=async()=>{const price=Number(customPrice);if(!price||price<0||!supabase)return;const {data,error:e}=await supabase.from('sales').insert({product_id:null,product_name:'Custom Item',price_charged:price,profit_recorded:0}).select().single();if(e)setError(e.message);else if(data)setSales(s=>[data as Sale,...s]);setCustomPrice('');setCustomOpen(false)};
 if(loading)return <main className="min-h-screen grid place-items-center bg-[#050914] text-sky-300">Loading Purabi Corner…</main>;
 return <main className="min-h-screen bg-[radial-gradient(circle_at_top,rgba(19,78,123,.22),transparent_35%),#050914] pb-24 text-white"><header className="sticky top-0 z-30 border-b border-white/5 bg-[#050914]/90 backdrop-blur-xl"><div className="mx-auto flex max-w-7xl items-center justify-between px-4 py-4"><div><p className="text-xs uppercase tracking-[.28em] text-sky-400">Purabi Corner</p><h1 className="text-xl font-semibold">Dairy POS Console</h1></div><div className="hidden items-center gap-2 rounded-full border border-white/10 px-4 py-2 text-sm text-slate-300 md:flex"><Receipt size={16}/> {todaySales.length} bills today</div></div></header><div className="mx-auto max-w-7xl px-4 pt-4">{error&&<div className="mb-4 flex items-center justify-between rounded-2xl border border-red-400/20 bg-red-400/10 px-4 py-3 text-sm text-red-300">{error}<button onClick={()=>setError('')}><X size={16}/></button></div>}{tab==='counter'&&<Counter products={products} counts={counts} total={total} add={add} remove={remove} custom={()=>setCustomOpen(true)} day={today}/>} {tab==='history'&&<History date={historyDate} setDate={setHistoryDate} rows={hist}/>} {tab==='analytics'&&<Analytics mode={mode} setMode={setMode} daily={daily} setDaily={setDaily} month={month} setMonth={setMonth} year={year} setYear={setYear} cs={cs} setCs={setCs} ce={ce} setCe={setCe} sales={asales} revenue={revenue} profit={profit}/>} {tab==='menu'&&<MenuManager products={products} setProducts={setProducts} editing={editing} setEditing={setEditing}/>}</div><nav className="fixed bottom-0 left-0 right-0 z-40 border-t border-white/10 bg-[#07101d]/95 backdrop-blur-xl"><div className="mx-auto grid max-w-3xl grid-cols-4">{([['counter','Counter',LayoutGrid],['history','History',Clock3],['analytics','Analytics',BarChart3],['menu','Menu',Menu]] as const).map(([k,l,I])=><button key={k} onClick={()=>setTab(k)} className={`flex flex-col items-center gap-1 px-2 py-3 text-xs ${tab===k?'text-sky-300':'text-slate-500'}`}><I size={19}/><span>{l}</span></button>)}</div></nav>{customOpen&&<div className="fixed inset-0 z-50 flex items-end justify-center bg-black/60 p-4 md:items-center"><div className="w-full max-w-md rounded-3xl border border-white/10 bg-[#0b1422] p-5"><div className="mb-4 flex justify-between"><h2 className="font-semibold">Custom item</h2><button onClick={()=>setCustomOpen(false)}><X size={18}/></button></div><input autoFocus value={customPrice} onChange={e=>setCustomPrice(e.target.value)} inputMode="decimal" placeholder="₹0" className="w-full rounded-2xl border border-white/10 bg-black/20 px-4 py-3"/><button onClick={custom} className="mt-4 w-full rounded-2xl bg-sky-400 py-3 font-semibold text-slate-950">Add to sale</button></div></div>}</main>;
}
function Counter({products,counts,total,add,remove,custom,day}:{products:Product[];counts:Record<string,number>;total:number;add:(p:Product)=>void;remove:(p:Product)=>void;custom:()=>void;day:string}){return <section><div className="mb-5 rounded-3xl border border-sky-400/20 bg-white/[.03] p-5"><div className="flex justify-between"><div><p className="text-[10px] uppercase tracking-[.2em] text-sky-400">Business Day</p><p className="text-sm">{formatBusinessDay(day)}</p></div><span className="rounded-full border border-white/10 px-3 py-1 text-[10px] text-slate-400">03:00 AM reset</span></div><p className="mt-4 text-xs uppercase tracking-widest text-slate-400">Live Daily Sales Total</p><p className="mt-1 text-4xl font-semibold">{money(total)}</p></div><div className="grid grid-cols-3 gap-2 md:grid-cols-3 lg:grid-cols-4">{products.map(p=><div key={p.id} className="overflow-hidden rounded-2xl border border-white/10 bg-white/[.03] p-2"><div className="aspect-square overflow-hidden rounded-xl bg-slate-900">{p.image_url?<img src={p.image_url} alt="" className="h-full w-full object-cover"/>:<div className="grid h-full place-items-center text-xs text-slate-600"><ImagePlus/></div>}</div><p className="mt-2 truncate text-sm font-medium">{p.name}</p><p className="text-xs text-slate-400">{money(p.price)}</p><div className="mt-2 flex gap-1"><button onClick={()=>remove(p)} disabled={!counts[p.id]} className="grid h-10 w-10 place-items-center rounded-xl border border-white/10 disabled:opacity-25"><Minus size={16}/></button><button onClick={()=>add(p)} className="flex-1 rounded-xl bg-sky-400 text-sm font-semibold text-slate-950"><Plus size={15} className="inline"/> Sell</button></div><p className="mt-1 text-center text-[10px] text-sky-300">{counts[p.id]||0} sold</p></div>)}</div><button onClick={custom} className="fixed bottom-24 right-4 rounded-2xl bg-sky-400 px-4 py-3 font-semibold text-slate-950">+ Custom</button></section>}
function History({date,setDate,rows}:{date:string;setDate:(x:string)=>void;rows:Sale[]}){return <section><div className="mb-5 flex items-end justify-between gap-3"><div><p className="text-xs uppercase tracking-widest text-slate-500">Transactions</p><h2 className="text-2xl font-semibold">History</h2></div><input type="date" value={date} onChange={e=>setDate(e.target.value)} className="rounded-2xl border border-white/10 bg-white/[.04] px-3 py-2 text-sm"/></div><div className="space-y-2">{rows.map((s,i)=><div key={s.id} className="flex items-center justify-between rounded-2xl border border-white/10 bg-white/[.03] px-4 py-3"><div><p className="font-medium">{s.product_name}</p><p className="text-xs text-slate-500">{new Date(s.timestamp).toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit'})}</p></div><p className="font-semibold">{money(s.price_charged)}</p></div>)}{!rows.length&&<div className="rounded-3xl border border-white/10 p-10 text-center text-slate-500">No sales on this date.</div>}</div></section>}
function Analytics({mode,setMode,daily,setDaily,month,setMonth,year,setYear,cs,setCs,ce,setCe,sales,revenue,profit}:{mode:Mode;setMode:(x:Mode)=>void;daily:string;setDaily:(x:string)=>void;month:string;setMonth:(x:string)=>void;year:string;setYear:(x:string)=>void;cs:string;setCs:(x:string)=>void;ce:string;setCe:(x:string)=>void;sales:Sale[];revenue:number;profit:number}){const chart=useMemo(()=>{const m=new Map<string,number>();sales.forEach(s=>{const k=businessDayKey(new Date(s.timestamp));m.set(k,(m.get(k)||0)+s.price_charged)});return [...m].sort().map(([date,value])=>({date:date.slice(5),revenue:value}))},[sales]);const top=useMemo(()=>{const m=new Map<string,{count:number;profit:number}>();sales.forEach(s=>{const x=m.get(s.product_name)||{count:0,profit:0};x.count++;x.profit+=s.profit_recorded;m.set(s.product_name,x)});return [...m].map(([name,v])=>({name,...v})).sort((a,b)=>b.count-a.count).slice(0,8)},[sales]);return <section><div className="mb-5 flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs uppercase tracking-widest text-slate-500">Performance</p><h2 className="text-2xl font-semibold">Analytics</h2></div><div className="grid grid-cols-4 gap-1 rounded-2xl border border-white/10 p-1">{(['daily','monthly','custom','yearly'] as Mode[]).map(x=><button key={x} onClick={()=>setMode(x)} className={`rounded-xl px-2 py-2 text-xs ${mode===x?'bg-sky-400 text-slate-950':'text-slate-400'}`}>{x[0].toUpperCase()+x.slice(1)}</button>)}</div></div><div className="mb-4 rounded-3xl border border-white/10 bg-white/[.03] p-4">{mode==='daily'&&<input type="date" value={daily} onChange={e=>setDaily(e.target.value)}/>} {mode==='monthly'&&<input type="month" value={month} onChange={e=>setMonth(e.target.value)}/>} {mode==='yearly'&&<input type="number" value={year} onChange={e=>setYear(e.target.value)} className="w-28"/>} {mode==='custom'&&<div className="flex gap-2"><input type="date" value={cs} onChange={e=>setCs(e.target.value)}/><input type="date" value={ce} onChange={e=>setCe(e.target.value)}/></div>}</div><div className="grid grid-cols-2 gap-3 md:grid-cols-3"><K title="Revenue" value={money(revenue)}/><K title="Profit" value={money(profit)}/><K title="Transactions" value={String(sales.length)}/></div><div className="mt-4 h-64 rounded-3xl border border-white/10 bg-white/[.03] p-3"><ResponsiveContainer width="100%" height="100%"><BarChart data={chart}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="date"/><YAxis/><Tooltip/><Bar dataKey="revenue"/></BarChart></ResponsiveContainer></div><div className="mt-4 rounded-3xl border border-white/10 bg-white/[.03] p-4"><h3 className="mb-3 font-semibold">Top selling items</h3>{top.map(x=><div key={x.name} className="flex justify-between border-b border-white/5 py-2 text-sm"><span>{x.name}</span><span>{x.count} · {money(x.profit)} profit</span></div>)}{!top.length&&<p className="text-sm text-slate-500">No sales in this period.</p>}</div></section>}
function K({title,value}:{title:string;value:string}){return <div className="rounded-2xl border border-white/10 bg-white/[.03] p-4"><p className="text-xs text-slate-500">{title}</p><p className="mt-1 text-2xl font-semibold">{value}</p></div>}
